module.exports = {
  apps: [
    {
      name: 'mark-website',
      script: 'website/server.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/website-error.log',
      out_file: '/opt/mark-agent/logs/website-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-telegram',
      script: 'telegram/bot.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/telegram-error.log',
      out_file: '/opt/mark-agent/logs/telegram-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-twitter',
      script: 'twitter/agent.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/twitter-error.log',
      out_file: '/opt/mark-agent/logs/twitter-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-discord',
      script: 'discord/bot.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/discord-error.log',
      out_file: '/opt/mark-agent/logs/discord-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-email',
      script: 'email/agent.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/email-error.log',
      out_file: '/opt/mark-agent/logs/email-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-treasury',
      script: 'treasury/manager.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/treasury-error.log',
      out_file: '/opt/mark-agent/logs/treasury-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-outreach',
      script: 'scripts/crypto-outreach.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/outreach-error.log',
      out_file: '/opt/mark-agent/logs/outreach-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-prelauncher',
      script: 'scripts/prelauncher.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 10000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/prelauncher-error.log',
      out_file: '/opt/mark-agent/logs/prelauncher-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-pricing',
      script: 'scripts/pricing-cron.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/pricing-error.log',
      out_file: '/opt/mark-agent/logs/pricing-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'mark-deposits',
      script: 'scripts/deposit-monitor.js',
      cwd: '/opt/mark-agent',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: { NODE_ENV: 'production' },
      error_file: '/opt/mark-agent/logs/deposits-error.log',
      out_file: '/opt/mark-agent/logs/deposits-out.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
